### ISSUE TITLE
BackTrack bypass

### ISSUE THREAD

**Issue by Jxhnn** [GrimAnticheat/Grim#1080]
### Describe the bypass and how to replicate it

How to replicate it ? Use backtrack cheat module (like in vape V4).

"Essentially a simple explanation is it allows you to hit the previous position of where a player was last at for a certain period of time."

It's the same effects of a reach hack.

### Grim version

2.3.38

### Server version

1.8

### Plugins

I tested it on "anticheat-test.com" server.

**Comment by c0dingnoobi** [comment]
basically https://github.com/GrimAnticheat/Grim/issues/545 
mentioned issue is not rlly helpful since video has been removed

**Comment by ghost** [comment]
Fix it by seeing if the lag is "possible" or not. Backtrack basically allows the player mimicking the lag by delaying the time without delaying other packets, this should be detectable.

**Comment by c0dingnoobi** [comment]
>  Backtrack basically allows the player mimicking the lag by delaying the time without delaying other packets,

was too lazy to send it again but ive wrote it once in discord:

> detecting backtrack in an open source anticheat is kind of useless (easy to bypass since u know what and how it checks)
backtrack basically is achieved by delaying incoming packets, so clientside your hitting an entity at an old position (reach < 3) which results in that reachy hit since serverside hes already out of those 3 blocks 
and tbh it would also be quite out of scope of grim since grim is more like an lag compensated anticheat (even if its tooo lag compensated at some points) and is not rlly a combat anticheat

and 

> in theory mitigating backtrack doesnt need to be mitigated with high ping 
ppl could just listen on positionupdate and check if the last transaction received is longer than x and increase a buffer
since delaying incoming will still send position updates 
it would fail for someone who is currently downloading anything since having lower downloading speed will eventually increase the time when client receives a packet (== incoming delay) 

what could be done is some kind of accuracy check which checks if the players only delays incoming when in theory it would give him an advantage (basically checking lag in relation to the distance to his opponent) 
but again
something like this is nonsense in an open source anticheat since cheaters could adjust their module an name it grimBacktrack and still have atleast the same amount of advantage

**Comment by SamB440** [comment]
2.0 will not have backtrack checks
