### ISSUE TITLE
Noslow by switchitem

### ISSUE THREAD

**Issue by z7087** [GrimAnticheat/Grim#1091]
### Describe the bypass and how to replicate it

Step 1. Use FDPClient
Step 2. Set Noslow mode to SwitchItem
work for blocking and consume

### Grim version

grimac-2.3.43

### Server version

Paper 1.8.8

### Plugins

GrimAC, ViaVersion, ViaBackwards

**Comment by c0dingnoobi** [comment]
has been touched at https://github.com/GrimAnticheat/Grim/commit/97a5ef99153173501713e325e97145e11e7c36fa when pe added `receivePacketSilently` due to changes in viaver 
caused issues with changing hotbar slotsw with bows https://github.com/GrimAnticheat/Grim/issues/874

so i doubt that this bypass will get fixed in near future

**Comment by MDevVal** [comment]
This is currently fixed.

**Comment by c0dingnoobi** [comment]
Its not, reopen this issue

**Comment by MDevVal** [comment]
I've tested on FDP client on a test server with latest grim. Are you sure you are not running an outdated version?

**Comment by c0dingnoobi** [comment]
ive tested it with augustus on latest grim (even the latest rn 16f2e5427c2044a0cc616334f46a8b345e03f36e) and it will bypass since there is no check in grim which is against this behaviour

**Comment by z7087** [comment]
https://github.com/z7087/AntiSwitchItem/releases
tested on spigot 1.8.8
