### ISSUE TITLE
Fence + soulsand

### ISSUE THREAD

**Issue by Souipi** [GrimAnticheat/Grim#1140]
### Describe the false positive and how to replicate it

Video 1 ( with a cheat ( hacked client)) : https://youtu.be/URQyXurf8d0

Video 2 ( without any cheat ( Optifine only )) : https://youtu.be/dbm6lz0KNmk

### Grim version

I tried on 2.3.43 and on the lastest build ( https://github.com/GrimAnticheat/Grim/actions/runs/5985586430 )

### Server version

Spigot/Paper 1.8.8 

### Plugins

GrimAC

**Comment by MWHunter** [comment]
Why are people suddenly reporting bugs again?

**Comment by ghost** [comment]
Because you have succeeded in creating a good piece of open source software, that is used by many users, and since the readme does not specify anything about issues not being accepted, *and* you still have tags and templates for these issues, people will obviously report them in the hopes they get fixed. 

It seems like you've had a relatively consistent issue stream with the "false positive" tag, too. If you no longer want to work on Grim, why not:
- make the fact that issues are no longer accepted by maintainers more clear
- ask for more maintainers in the readme
- archive the project on github
- merge any of the open PRs that (apparently, I haven't reviewed) fix various issues

You aren't obligated to provide support to anyone while doing open source work, but being actively disdainful towards them for reporting issues in the hope it will be useful seems like it goes against the spirit of open source.

**Comment by MWHunter** [comment]
There's been 7 issues in the past 30 hours.  The previous 7 issues were opened in the past 14 days.  It's just weird.

This issue will likely never be fixed because 1.8 is such an old version.

**Comment by ghost** [comment]
One of those issues is a troll and 4 of them were opened by the same person. Additionally, your response to #1133 shows the same thing.

**Comment by Hwaanx** [comment]
> There's been 7 issues in the past 30 hours. The previous 7 issues were opened in the past 14 days. It's just weird.
> 
> This issue will likely never be fixed because 1.8 is such an old version.

yeah its a version issue doesn't false on my server 1.19.4

**Comment by ghost** [comment]
It can maybe be fixed by changing CollisionData.

**Comment by ghost** [comment]
It happens because when you are in the fence and underneath you have a soulsand, Grim thinks that you had to be on the soulsand height but your client knows that you had to be in the fence height, so Grim flags.

**Comment by Souipi** [comment]
> It can maybe be fixed by changing CollisionData.

Sure pbly

**Comment by Souipi** [comment]
Someone has an idea to how patch that ? Because i think the problem is caused by soulsand collission. But idk what edit to do...
