### ISSUE TITLE
Tapping jump movement key while in lava.

### ISSUE THREAD

**Issue by 0-x-2-2** [GrimAnticheat/Grim#1167]
### Describe the false positive and how to replicate it

Eat golden apple.

Fall in a pit of lava and get submerged.

Tap the jump key while in the lava to flag the simulation check.

https://paste.grim.ac/OcbMm

### Grim version

https://github.com/GrimAnticheat/Grim/tree/16f2e5427c2044a0cc616334f46a8b345e03f36e

### Server version

```
This server is running Paper version git-Paper-477 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 5c78e77)
```

### Plugins

```
Server Plugins (3):
Bukkit Plugins:
 - GrimAC, ViaVersion, WorldEdit
 ```

**Comment by 0-x-2-2** [comment]
The client version in the log is 1.20.2 but the same issue happens with any 1.20.x client in my testing and should be identical.

**Comment by c0dingnoobi** [comment]
dup #1094 (even same offset)
safe to close to avoid issue tracking complexity

**Comment by 0-x-2-2** [comment]
> dup #1094 (even same offset) safe to close to avoid issue tracking complexity

> try swimming straight upwards in lava without fire resistance so you have damage tick

I am not actually sure these are 100% duplicates as the other one is the anti-kb check making most of the comments here misleading. It is more likely these are related, this issue gets even worse when moving the head and using the Elytra. You can get stuck in Lava while not taking any damage while having fire resistance.

**Comment by c0dingnoobi** [comment]
reason why im thinking that this is an duplicate is:
- we are talking about false positives in the same situations and same ways of reproducing the base issue
- it shouldnt matter if u flag antikb or simulation since both are from grims prediction engine itself, your provided gl seems to flag nearly the same [offset](https://paste.grim.ac/OcbMm#L608) as provided in the mentioned issue 

based of those two points, its not only a related issue, its most likely a duplicate issue which again is safe to close

its unlikely for grim to have these fixed in the current branch so two options left
either we wait for somone who pres it or we wait for 3.0

**Comment by 0-x-2-2** [comment]
> your provided gl seems to flag nearly the same [offset](https://paste.grim.ac/OcbMm#L608) as provided in the mentioned issue

I don't really see this, they are not really anywhere close to being the same offset, and looks like just a coincidence to me, I have seen many different values and the other issue provides much less information.

>  either we wait for somone who pres it or we wait for 3.0

That is kinda of the point of opening this issue. This issue has been pretty significant for players on our server who travel far in deep nether terrain. If this cannot be fixed properly in 2.0, it may be possible to hot-fix the problem as the illegal movement is very small and insignificant.

**Comment by c0dingnoobi** [comment]
ok so after further testing to verify if this is a duplicate or not:

you indeed fail *only simulation* when tapping only jump key while in lava with fire resistance. the offsets are 0.00940 up to 0.0196

now as said, my guess that this is a duplicate issue is because the mentioned issue fails the EXACTLY same offsets WITH ALSO antiKB WHEN the client doesnt have a fire resistance potion, the takes lava damage thus causing AntiKB flags due to client receiving velocity when getting damage. 

both issues are fundamentally caused by grim predicting the first ticks wrong when going upwards (pressing jump) while in lava
- you fail only simulation if you have any effect which neglates the velocity taken by lava (fire resistance)
- you fail antikb in addition to simulation if you take the velocity received by lava dmg

**Comment by c0dingnoobi** [comment]
fun fact, the first ticks are only calculated wrong if the input is only jump, if the input is any forward/backward/right/left key in addition to jump you dont fail *while in lava* instead you only fail when trying to jump out of the lava by being near a block edge (when having no fire resistance) probably caused by the setbacks caused when taken velocity

also when swimming towards a block with no fireresistance in lava, you fail groundspoof

**Comment by c0dingnoobi** [comment]
~~[related to](https://github.com/GrimAnticheat/Grim/blob/c33b80dc20921ed38fa4a88387dca21bbd1ce67e/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngineLava.java#L14C20-L14C20)~~
```java
    @Override
    public void addJumpsToPossibilities(GrimPlayer player, Set<VectorData> existingVelocities) {
        for (VectorData vector : new HashSet<>(existingVelocities)) {
            existingVelocities.add(new VectorData(vector.vector.clone().add(new Vector(0, 0.04f, 0)), vector, VectorData.VectorType.Jump));
```

~~Grim Debug:~~
![image](https://github.com/GrimAnticheat/Grim/assets/97745777/4f9f976a-21ad-4b81-acf2-6a0fff2105a1)
~~Can not gurantuee a fix but im working on it~~

Ok this is mcp 1:1..

**Comment by MWHunter** [comment]
Remember that mojang doesn't send a packet if you reach 0, 0, 0 velocity.  This is why grim isn't handling it correctly, the player is skipping a tick in a way we don't handle.

Basically let tick skip vectors have fluid jump (0.02) velocity addition.

Fuck mojang

**Comment by c0dingnoobi** [comment]
> Basically let tick skip vectors have fluid jump (0.02) velocity addition.

ig i could try to make this work
