### ISSUE TITLE
Multitask/autoblock checks

### ISSUE THREAD

**Issue by ManInMyVan** [GrimAnticheat/Grim#1195]
### Feature description

Add a check for if a player uses an item and breaks a block/attacks an entity, because to my knowledge, it is not possible to attack entities or (in versions after 1.7.10) mine blocks while using items.

**Comment by z7087** [comment]
https://github.com/GrimAnticheat/Grim/pull/1074

**Comment by c0dingnoobi** [comment]
> #1074

#1161 BadPacketsS

**Comment by z7087** [comment]
> > #1074
> 
> #1161 BadPacketsS

Hi, if that BadPacketsS falseless on 1.8, does this need to be changed? ~~or BadPacketsS never flag for sword?~~
https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/events/packets/PacketPlayerAttack.java#L39-L42

**Comment by c0dingnoobi** [comment]
> > > #1074
> > 
> > 
> > #1161 BadPacketsS
> 
> Hi, if that BadPacketsS falseless on 1.8, does this need to be changed? ~or BadPacketsS never flag for sword?~ https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/events/packets/PacketPlayerAttack.java#L39-L42

that line doesnt cause false positives instead it causes bypass mentioned in #1160 [explained in this comment](https://github.com/GrimAnticheat/Grim/issues/1160#issuecomment-1758730364)

using that cheat would still result in constantly getting slowed down since u never release the blocking clientside, it is basically useless unless the player uses switch item no slow in combination of this autoblock

**Comment by ManInMyVan** [comment]
> > #1074
> 
> #1161 BadPacketsS

Doesn't seem to be flagging me breaking blocks while blocking. Does flag me attacking entities while blocking though.

**Comment by c0dingnoobi** [comment]
> Doesn't seem to be flagging me breaking blocks while blocking. 

yea its only checking for interact/block
checking for block break while blocking would have to be exempted for 1.7 and 1.8 (clients such as badlion client since they will be able to false it using their oldanimation mod) 

means it would need to be implemnted for 1.9+ which might ("might" since ive never tested) be hard due to missing idle packet

**Comment by ManInMyVan** [comment]
> exempted for 1.7

Yes, vanilla 1.7 allows you to do this

> clients such as badlion client since they will be able to false it using their oldanimation mod

It doesn't let you actually break blocks using it, so a check for this could be similar to `on player break block -> if player is using item -> flag`

> implemnted for 1.9+

Same issue as before with 1.8 clients, old animations mods would flag (Not often they get used on 1.9+, but sometimes are)

**Comment by c0dingnoobi** [comment]
> It doesn't let you actually break blocks using it, so a check for this could be similar to on player break block -> if player is using item -> flag

ive already tried to debug it and it rlly does false it due to how bad bac is, its not reproduceable with lunar 1.8 with their old animations mod

just block and break a block using bac with oldanimations mod and it will send the packets which would need to be flagged, 1.8 lunar also breaks the blocks but its just clientside it doesnt tell the server that it digged a block

**Comment by ManInMyVan** [comment]
> > It doesn't let you actually break blocks using it, so a check for this could be similar to on player break block -> if player is using item -> flag
> 
> ive already tried to debug it and it rlly does false it due to how bad bac is, its not reproduceable with lunar 1.8 with their old animations mod
> 
> just block and break a block using bac with oldanimations mod and it will send the packets which would need to be flagged, 1.8 lunar also breaks the blocks but its just clientside it doesnt tell the server that it digged a block

As a proof of concept, I made this based on your BadBacketsS check:
```java
    public void onPacketReceive(PacketReceiveEvent event) {
        if (event.getPacketType() == PacketType.Play.Client.PLAYER_DIGGING) {
            if (player.packetStateData.slowedByUsingItem) {
                DiggingAction action = new WrapperPlayClientPlayerDigging(event).getAction();
                if (action == DiggingAction.FINISHED_DIGGING) {
                    if (flagAndAlert() && shouldModifyPackets()) {
                        event.setCancelled(true);
                        player.onPacketCancel();
                    }
                }
            }
        }
    }
```
and it doesn't false with BadLion (it also doesn't work with instamine blocks, doesn't resend the block to the client if they flag for some reason, can be bypassed w/ switchitem, and doesn't check if the player is on pre-1.8)
