### ISSUE TITLE
Simulation false when switching to/from an item with efficiency enchant

### ISSUE THREAD

**Issue by Jyguy** [GrimAnticheat/Grim#1627]
### Describe the false positive and how to replicate it

1. Use a non-1.20.5/6 client on a 1.20.6 server (e.g. 1.20.4, 1.21)
2. Give yourself a pickaxe with efficiency
3. Switch between the pickaxe and another item while sprinting
4. Observe the false until you stop moving

https://github.com/user-attachments/assets/2f2e0493-4717-4000-84fa-700cb793fc04

`/gl 1` output from the video: https://paste.grim.ac/dyqqros

I could not reproduce this at all on a 1.21 server (tested 1.21, 1.20.6, 1.20.4, and 1.17.1 clients).

### Grim version

0b058c1

### Server version

This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### Plugins

```
Bukkit Plugins:
- GrimAC, ViaBackwards, ViaVersion
```

ViaBackwards & ViaVersion are both 5.0.2

**Comment by SamB440** [comment]
as far as I'm aware, this is a via issue, and we will not be fixing this

**Comment by SamB440** [comment]
https://github.com/ViaVersion/ViaVersion/blob/master/bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/v1_20_5to1_21/PlayerChangeItemListener.java

This is probably the problem, it's likely there's an issue with the attribute handling which is resetting the sprinting attribute or changing some speed-related attribute that Grim doesn't know about because it's behind Via.
