### ISSUE TITLE
Using freecam to phase through doors and other blocks

### ISSUE THREAD

**Issue by AbdisKiosk** [GrimAnticheat/Grim#1800]
### Describe the bypass and how to replicate it

Step 1. Break the door using freecam (I am using Vape V4 in my example)
Step 2. Try to go through the door you just broke
Step 3. Have another player hit you through the door

Example video here:
https://github.com/user-attachments/assets/da36105f-654a-4cb4-9983-b4096ecc3aa7

### Grim version

Latest commit at this time, c749a56

### Server version

1.8.8, PandaSpigot

### Plugins

GrimAC

**Comment by Axionize** [comment]
Does this still work if you turn off building on ghost blocks in your grim config?

**Comment by AbdisKiosk** [comment]
~~I’m sorry for the wasting your time, but I’ve found that this issue only occurs on LightningGrim. It doesn’t seem happen with the official GrimAC build, even if `allow-building-on-ghostblocks` is set to true. I will be creating my issue there instead.~~

**Comment by AbdisKiosk** [comment]
I was able to reproduce it on the official GrimAC with both `allow-building-on-ghostblocks=true` and `allow-building-on-ghostblocks=false`.

**Comment by ManInMyVan** [comment]
try setting `moved-wrongly-threshold` in your spigot.yml to 0

**Comment by SamB440** [comment]
> try setting `moved-wrongly-threshold` in your spigot.yml to 0

We really should warn about this on startup regardless. Could also use hacky reflection to force change it, but I'd rather not.

**Comment by AbdisKiosk** [comment]
I tried setting it to 0, however it seems to break some movement such as moving inside cobweb

**Comment by SamB440** [comment]
Oh you meant lowering the threshold, not increasing it... usually I disable it entirely because it causes setback issues

**Comment by ManInMyVan** [comment]
> I tried setting it to 0, however it seems to break some movement such as moving inside cobweb

raise it until that doesn't happen

**Comment by AbdisKiosk** [comment]
> > I tried setting it to 0, however it seems to break some movement such as moving inside cobweb
> 
> raise it until that doesn't happen

If I raise it until it doesn't happen, I am able to go through the door.

I think the issue might have to due with Grim's replication of the player's world view, as I am able to hit through these blocks while using Lightninggrim.

**Comment by 483378** [comment]
The only "cheating" behavior here I see is breaking the door from too far away. We should catch this with FarBreak/RotationBreak/PositionBreak checks. Moving through blocks that don't exist on the client is legitimate. During testing, I found out that this also works when breaking the blocks and using Blink instead of Freecam so the blocks aren't being replaced, so there would still be a way to bypass this even with break checks. In my opinion, there are only two ways to patch this:

1. Setback (don't flag) when moving into/through blocks that exist on the server but not on the client. This will patch the issue but might make combat that involves the opponent placing blocks less enjoyable for high ping players because the setbacks might not be exactly like the vanilla ones which will occur in high ping block placement combat. Some other anticheats also do this.
2. Ignore the problem and leave everything as it is. This is only a problem if the player can move fast enough to go through the block in one go (e.g. by knockback or high movement speed). If the player can only do a small step into the block (walk speed), vanilla will set them back. If they don't take kb or have a high speed attribute this cannot be exploited directly, so it might not be an issue in most cases (e.g. areas where PvP is disabled).

**Comment by ManInMyVan** [comment]
> FarBreak/RotationBreak/PositionBreak

#1639

**Comment by AbdisKiosk** [comment]
> > FarBreak/RotationBreak/PositionBreak
> 
> #1639
Just tested with this PR. It solves the issue.

**Comment by ManInMyVan** [comment]
should be fixed by FarBreak
