### ISSUE TITLE
Slow timer doesn't flag

### ISSUE THREAD

**Issue by booky10** [GrimAnticheat/Grim#636]
**Describe the bug**
If you slowdown your game (doesn't matter how much, tested with 50% and 0.5%, 200% timer is detected) Grim doesn't do anything.
Was already reported in the discord, but didn't see a GitHub issue for it.

**To Reproduce**
https://youtu.be/Aorp58nR3Lk

**Server Version:**
`test.grim.ac`

**Grim Version (Git commit or the version in the jar's name)**
`test.grim.ac`

**Relevant plugins**
`test.grim.ac`

**Comment by ghost** [comment]
I don't think grim was advertised as detecting slowdown timer as that is much harder to do than speedup timer due to many factors.

**Comment by MWHunter** [comment]
It's possible because grim knows when a player "loses" time which is used in the timer check to stop 1.9+ players from going excessively fast after standing still.

Just needs the logic to attach Timer to Predictions, which knows if it was physically possible for a player to not have made a movement, such as when they are falling.

**Comment by MWHunter** [comment]
Fixed by https://github.com/GrimAnticheat/Grim/commit/bfe3d8c57e783e023bd4eac89c33d9060df81cac
