### ISSUE TITLE
Anti AutoTotem And Anti Trigger Bot

### ISSUE THREAD

**Issue by xXCooBloyXx** [GrimAnticheat/Grim#799]
### Feature description

Hello, i suggest to add 2 new cheats detect:
auto totem - when your totem is used, another one is set up immediately (you can change the delay in wurst)
trigger bot - when turned on, when the player is on your cursor automatically damage him, a bit like aim bot + auto clicker but without automatic aiming

**Comment by TawnyE** [comment]
"Due to both technical limitations with the current engine design and mojang's complete stupidity with netcode, only major issues will be fixed. Minor issues will be ignored. By using Grim, you are expected to either fix issues you encounter or pay someone to do so, or ignore them. I can no longer provide support, for thousands of people, for free." I think you missed a little thing.
