### ISSUE TITLE
NegativeTimer

### ISSUE THREAD

**Issue by niemogewejsc** [GrimAnticheat/Grim#892]
### Describe the false positive and how to replicate it

https://streamable.com/ydu39x

![image](https://user-images.githubusercontent.com/93555429/210158220-5938e454-e784-4720-b7bc-0858bffb6d69.png)

hit a player to get him banned, idk
yes, these are vanilla clients

### Grim version

2.3.32

### Server version

git-Paper-366 1.19.3

### Plugins

GrimAC, LuckPerms

**Comment by c0dingnoobi** [comment]
first of all:
- it is unable to find that log since super debug only works for simulation logs and not for negativetimer
- you should not ban for negativetimer (probably many other checks too) since they are not intended to ban [see here](https://github.com/MWHunter/Grim/wiki/Design-Philosophy)

i am assuming client somehow ticks slower when not tabbed in which might be the cause for these falses.

**Comment by niemogewejsc** [comment]
ok, thanks for the clarification
